/**
 * A minimal but valid glTF 2.0 binary (single triangle, default material), used
 * by {@link MockGenerator} as its stand-in "generated" output until World Labs
 * Atlas is wired in. Generated by `scripts` in the milestone-3 notes; edit there,
 * not here.
 */
export const SAMPLE_GLB_BASE64 =
  "Z2xURgIAAABcAgAAHAIAAEpTT057ImFzc2V0Ijp7InZlcnNpb24iOiIyLjAiLCJnZW5lcmF0b3IiOiIzREFJIE1vY2tHZW5lcmF0b3Igc2FtcGxlIn0sInNjZW5lIjowLCJzY2VuZXMiOlt7Im5vZGVzIjpbMF19XSwibm9kZXMiOlt7Im1lc2giOjAsIm5hbWUiOiJzYW1wbGUifV0sIm1lc2hlcyI6W3sibmFtZSI6InNhbXBsZSIsInByaW1pdGl2ZXMiOlt7ImF0dHJpYnV0ZXMiOnsiUE9TSVRJT04iOjB9LCJtb2RlIjo0fV19XSwibWF0ZXJpYWxzIjpbeyJuYW1lIjoic2FtcGxlIiwicGJyTWV0YWxsaWNSb3VnaG5lc3MiOnsiYmFzZUNvbG9yRmFjdG9yIjpbMC42LDAuNiwwLjcsMV19fV0sImJ1ZmZlcnMiOlt7ImJ5dGVMZW5ndGgiOjM2fV0sImJ1ZmZlclZpZXdzIjpbeyJidWZmZXIiOjAsImJ5dGVPZmZzZXQiOjAsImJ5dGVMZW5ndGgiOjM2LCJ0YXJnZXQiOjM0OTYyfV0sImFjY2Vzc29ycyI6W3siYnVmZmVyVmlldyI6MCwiYnl0ZU9mZnNldCI6MCwiY29tcG9uZW50VHlwZSI6NTEyNiwiY291bnQiOjMsInR5cGUiOiJWRUMzIiwibWluIjpbMCwwLDBdLCJtYXgiOlsxLDEsMF19XX0gICAkAAAAQklOAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAIA/AAAAAA==";

/** The decoded sample as bytes. */
export function sampleGlb(): Buffer {
  return Buffer.from(SAMPLE_GLB_BASE64, "base64");
}
